# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20170501_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_bid',
            field=models.IntegerField(default=0),
        ),
    ]
